### ISSUE TITLE
Issue with reading format

### ISSUE THREAD

**Issue by DarkmatterVale** [HaikuArchives/Tipster#1]
For some reason, using "\n%\n" as a delimiter for string parsing & separating is not working. In the end, after the tips file is read in, the above will leave a "%\n" in each string.

To get around this, I am currently using https://github.com/DarkmatterVale/Tipster/blob/master/Tipster/Tipster.cpp#L157 to remove that line from the string.

**Comment by janus2** [comment]
This should be a problem with Haiku split. I have opened a ticket see https://dev.haiku-os.org/ticket/14045
