### ISSUE TITLE
No tips in window

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Tipster#13]
Built Tipster from haikuports recipe.
Upon launching the app no tips apppear in the window

**Comment by ohnx** [comment]
Hi!

Tipster expects tips to be in the folder `Tipster` and each tip file to be in the format `tips-<lang>`

My guess is that your tips aren't loading correctly since they aren't in the right folder; in fact, for this repository, the tips are located in the folder `tips`, which won't work.

**Comment by humdingerb** [comment]
Nope. To me https://github.com/HaikuArchives/Tipster/blob/master/source/Tipster.cpp#L452 looks like it's looking into B_FIND_PATH_DATA_DIRECTORY/tipster-tips/ and the used recipe is wrong.
IMO this issue is not one of Tipster.

**Comment by janus2** [comment]
Is this an improvement?

![tipster](https://user-images.githubusercontent.com/10423645/36760984-48771468-1c1d-11e8-83c3-1c93a4154afb.png)

**Comment by humdingerb** [comment]
From no tips in the window to one tip in the window... I'd say so. :)
@janus2, you have the honour of closing the ticket.

**Comment by janus2** [comment]
Thanks...
