### ISSUE TITLE
64bit version gets locale wrong

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Tipster#23]
At https://github.com/HaikuArchives/Tipster/blob/master/source/Tipster.cpp#483 Tipster gets back "en_150" under 64bit, under 32bit it's the expected "en".

The tips file name then isn't found.

**Comment by janus2** [comment]
Strange worked for me...

**Comment by humdingerb** [comment]
User error. Kinda...
I had "English (Europe)" set in the Locale prefs. Which is, correctly, "en_150".
Closing the ticket. Maybe I should open a ne enhacement for a smart fallback to the common "en" locale name...
