### ISSUE TITLE
Typo found in tips-en.txt

### ISSUE THREAD

**Issue by unspacyar** [HaikuArchives/Tipster#26]
Translating the tips-en.txt content, I found the following tip at line # 96:

"Use keyboard's Page↑ / Page↓ and Home/End to quickly navigate the context menu in a very crowded folder."

I'm not sure if that keys do anything in the context menu.  I guess that is used just inside the Tracker file list.

**Comment by humdingerb** [comment]
Thanks @unspacyar!
I improved the wording. The tip is about the drill-down context menu, in case there was a confusion before.

@unspacyar, @janus2:
I made a few more small changes in d24e15c. Please have a look if you have to change the es/it translations.

**Comment by humdingerb** [comment]
Oh, and I was sure it also used to work with the Home/End keys before. Not anymore...

**Comment by unspacyar** [comment]
@humdingerb your welcome!  In the next days I will end the spanish translation.

**Comment by unspacyar** [comment]
@humdingerb Hello again.  I'm attaching the tips-es.txt file.  I tried to do a pull-request, but don't managed to do it correctly. Sorry!
[tips-es.txt](https://github.com/HaikuArchives/Tipster/files/1911510/tips-es.txt)
