### ISSUE TITLE
 There is no "OPT" key

### ISSUE THREAD

**Issue by probonopd** [HaikuArchives/Tipster#29]
https://github.com/HaikuArchives/Tipster/blob/df750b0aaf7ca5ebce216d78b4f533d5b0199d3a/tips/tips-en.txt#L10

There is no "OPT" key on PC keyboards.

**Comment by humdingerb** [comment]
In Haiku's GUI and all documentation, the key is called "OPT". Other OS call it "Super", "Meta" or -- weirdly :) -- "Windows" key.

**Comment by probonopd** [comment]
Aaah. „Meta“ I would have understood. But let’s stay consistent then.
