### ISSUE TITLE
Fix previous tip

### ISSUE THREAD

**Issue by DarkmatterVale** [HaikuArchives/Tipster#7]
The current implementation is quite poor and a better solution will need to be found.

Ideas are welcome.

**Comment by humdingerb** [comment]
My idea would be:
- get the number of available tips
- create an array with those tips numbers
- randomize the elements in that array
- create another of such a randomized array 
- go from element to element in those two arrays and fetch and display the respective tip
- when you're at the end of the 2nd array, it becomes the new 1st array. Create a new 2nd array and continue. Extra points for making sure the next two tips of the new 2nd array aren't the same as the last two of the new 1st array, so tips aren't too obviously repeated.

That way you always have a "history" of old tips you can go back to that's as along as the number of tips. More that enough, I'd say.
